FROM node:12
WORKDIR /app
ADD ./app /app
RUN npm install
EXPOSE 3000

ARG DATABASE_HOSTNAME
ARG DATABASE_USERNAME

ENV DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
ENV DATABASE_USERNAME=${DATABASE_USERNAME}
CMD npm start