apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
    traffic.spinnaker.io/load-balancers: '["service demoapp"]'
  labels:
    app: demoapp
    env: dev
  name: demoapp
  namespace: demo-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
      env: dev
  template:
    metadata:
      labels:
        app: demoapp
        env: dev
    spec:
      containers:
      - name: demoapp
        image: 787278094283.dkr.ecr.us-east-2.amazonaws.com/ca-node-demo:${parameters.imageTag}
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        ports:
        - containerPort: 3000
          name: demoapp-port