apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: demo-service
  labels:
    app: demoapp
    env: dev
spec:
  selector:
    matchLabels:
      app: demoapp
      env: dev
  replicas: 3
  template:
    metadata:
      labels:
        app: demoapp
        env: dev
    spec:
      containers:
      - name: demoapp
        image: 787278094283.dkr.ecr.us-east-2.amazonaws.com/ca-node-demo
        resources:
          # requests:
          #   cpu: 500m
          #   memory: 100Mi
          limits:
            cpu: 1000m
            memory: 200Mi
        ports:
        - containerPort: 3000
          name: demoapp-port
---
apiVersion: v1
kind: Service
metadata:
  name: demoapp
  namespace: demo-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  ports:
    - port: 80
      targetPort: demoapp-port
      protocol: TCP
  selector:
    app: demoapp
  type: LoadBalancer
---
apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: demoapp-vpa
  namespace: demo-service
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demoapp
  resourcePolicy:
    containerPolicies:
      - containerName: '*'
        minAllowed:
          cpu: 100m
          memory: 50Mi
        maxAllowed:
          cpu: 1
          memory: 500Mi
        controlledResources: ["cpu", "memory"]

