apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: demo-service-gateway
  namespace: default
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-service
  namespace: default
spec:
  hosts:
  - "a338e3f50f40e4f04b71543a9a4bf96b-2092078052.us-east-2.elb.amazonaws.com"
  gateways:
  - "default/demo-service-gateway"
  http:
  - match:
    - uri:
        exact: /product
    rewrite:
      uri: /
    route:
    - destination:
        host: demoapp.default.svc.cluster.local
